# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-10 12:16

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import django_pricemanager.models.channel
import django_pricemanager.models.pricelist


# Data operations from the replaced chain are intentionally NOT carried over — all three were
# one-off conversions of pre-existing rows, no-ops on a fresh database:
#   0016_convert_countryfield_to_country — moved django_countries codes into django_regional FKs
#   0022_currency_to_regional            — re-pointed currency FKs to django_regional.Currency
#   0023_purchasecost_and_supplier_cost_backfill — moved legacy supplier costs into PurchaseCost
class Migration(migrations.Migration):
    replaces = [
        ("django_pricemanager", "0001_initial"),
        ("django_pricemanager", "0002_currency_name_currency_sign"),
        ("django_pricemanager", "0003_channel_remove_salechannel_sale_channel_shop_and_more"),
        ("django_pricemanager", "0004_price_tax_rate"),
        ("django_pricemanager", "0005_alter_taxclass_idx"),
        ("django_pricemanager", "0006_alter_productrepresentation_sku"),
        ("django_pricemanager", "0007_alter_productrepresentation_sku_and_more"),
        ("django_pricemanager", "0008_price_special_from_date_price_special_to_date"),
        ("django_pricemanager", "0009_salechannel_is_only_for_verified_user_and_more"),
        ("django_pricemanager", "0010_customerrepresentation_and_more"),
        ("django_pricemanager", "0011_attributerepresentation_alter_price_unique_together_and_more"),
        ("django_pricemanager", "0012_alter_price_special_from_date_and_more"),
        ("django_pricemanager", "0013_priceattribute_alter_price_options_and_more"),
        ("django_pricemanager", "0014_channel_calculate_countries"),
        ("django_pricemanager", "0015_price_product_parent"),
        ("django_pricemanager", "0016_convert_countryfield_to_country"),
        ("django_pricemanager", "0017_alter_taxrate_rate"),
        ("django_pricemanager", "0018_price_created_at_price_updated_at"),
        ("django_pricemanager", "0019_v3_currentprice_pricehistory"),
        ("django_pricemanager", "0020_pricemanager_settings"),
        ("django_pricemanager", "0021_currentprice_supplier_cost"),
        ("django_pricemanager", "0022_currency_to_regional"),
        ("django_pricemanager", "0023_purchasecost_and_supplier_cost_backfill"),
        ("django_pricemanager", "0024_remove_currentprice_supplier_cost_fields"),
    ]

    initial = True

    dependencies = [
        ("django_regional", "0001_squashed_0006_country_default_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeRepresentation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name_plural": "attr representations",
                "ordering": ["idx"],
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("net_value", models.DecimalField(decimal_places=4, max_digits=19)),
                ("gross_value", models.DecimalField(decimal_places=4, max_digits=19)),
                ("special_net_value", models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ("special_gross_value", models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ("special_from_date", models.DateTimeField(blank=True, default=None, null=True)),
                ("special_to_date", models.DateTimeField(blank=True, default=None, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PriceManagerSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "matrix_signals_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable automatic Matrix read model sync on price changes"
                    ),
                ),
                (
                    "read_from_current",
                    models.BooleanField(
                        default=False, help_text="Read prices from CurrentPrice instead of legacy PriceList"
                    ),
                ),
            ],
            options={
                "verbose_name": "PriceManager Settings",
                "verbose_name_plural": "PriceManager Settings",
            },
        ),
        migrations.CreateModel(
            name="ProductRepresentation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name_plural": "products representations",
                "ordering": ["sku"],
            },
        ),
        migrations.CreateModel(
            name="TaxClass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("source_file", models.FileField(blank=True, null=True, upload_to="pricelists")),
            ],
            options={
                "verbose_name_plural": "tax classes",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                (
                    "calculate_direction",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Calculate prices from netto to gross"),
                            (1, "Calculate prices from gross to netto"),
                        ],
                        default=django_pricemanager.models.channel.CalculateDirectionEnum["FROM_NET_TO_GROSS"],
                    ),
                ),
                (
                    "calculate_countries",
                    models.ManyToManyField(
                        blank=True, related_name="calculate_countries_channels", to="django_regional.country"
                    ),
                ),
                (
                    "default_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="django_regional.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "channels",
                "ordering": ["idx"],
            },
        ),
        migrations.CreateModel(
            name="CurrentPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "net_value",
                    models.DecimalField(
                        decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "gross_value",
                    models.DecimalField(
                        decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "special_net_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "special_gross_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("special_from_date", models.DateTimeField(blank=True, default=None, null=True)),
                ("special_to_date", models.DateTimeField(blank=True, default=None, null=True)),
                ("is_only_for_verified_user", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("csv_import", "CSV Import"),
                            ("api", "API"),
                            ("generation", "Generation"),
                            ("admin_edit", "Admin Edit"),
                            ("tax_rate_change", "Tax Rate Change"),
                            ("migration", "Migration"),
                            ("migration_backfill", "Migration Backfill"),
                            ("supplier_cost", "Supplier Cost"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_prices",
                        to="django_pricemanager.channel",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_regional.country"),
                ),
                (
                    "currency",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_regional.currency"),
                ),
            ],
            options={
                "verbose_name": "current price",
                "verbose_name_plural": "current prices",
                "db_table": "pricemanager_currentprice",
            },
        ),
        migrations.CreateModel(
            name="CurrentPriceAttribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_price_attrs",
                        to="django_pricemanager.attributerepresentation",
                    ),
                ),
                (
                    "current_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_attrs",
                        to="django_pricemanager.currentprice",
                    ),
                ),
            ],
            options={
                "db_table": "pricemanager_currentpriceattribute",
                "unique_together": {("current_price", "attr")},
            },
        ),
        migrations.AddField(
            model_name="currentprice",
            name="attrs",
            field=models.ManyToManyField(
                blank=True,
                related_name="current_prices_attrs",
                through="django_pricemanager.CurrentPriceAttribute",
                to="django_pricemanager.attributerepresentation",
            ),
        ),
        migrations.CreateModel(
            name="CustomerRepresentation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.CharField(max_length=128)),
                ("user_email", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name_plural": "customers representations",
                "constraints": [models.UniqueConstraint(models.F("uid"), name="unique_pricemanager_customer_uid")],
            },
        ),
        migrations.AddField(
            model_name="currentprice",
            name="customer_representation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_prices",
                to="django_pricemanager.customerrepresentation",
            ),
        ),
        migrations.CreateModel(
            name="PriceAttribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_attributes",
                        to="django_pricemanager.attributerepresentation",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_attributes",
                        to="django_pricemanager.price",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="price",
            name="attrs",
            field=models.ManyToManyField(
                blank=True,
                related_name="prices_attrs",
                through="django_pricemanager.PriceAttribute",
                to="django_pricemanager.attributerepresentation",
            ),
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                ("source_file", models.FileField(blank=True, upload_to="pricelists")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "Error"), (1, "Ready"), (2, "In progress")],
                        db_index=True,
                        default=django_pricemanager.models.pricelist.PriceListStatusEnum["IN_PROGRESS"],
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_regional.country"),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricelists_currency_ref",
                        to="django_regional.currency",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_on",
            },
        ),
        migrations.AddField(
            model_name="price",
            name="pricelist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="prices", to="django_pricemanager.pricelist"
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="django_pricemanager.productrepresentation",
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="product_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_prices",
                to="django_pricemanager.productrepresentation",
            ),
        ),
        migrations.AddField(
            model_name="currentprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_prices",
                to="django_pricemanager.productrepresentation",
            ),
        ),
        migrations.AddField(
            model_name="currentprice",
            name="product_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_child_prices",
                to="django_pricemanager.productrepresentation",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseCost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "net_cost",
                    models.DecimalField(
                        decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("supplier_idx", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_costs",
                        to="django_pricemanager.channel",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_regional.country"),
                ),
                (
                    "currency",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_regional.currency"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_costs",
                        to="django_pricemanager.productrepresentation",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase cost",
                "verbose_name_plural": "purchase costs",
                "db_table": "pricemanager_purchasecost",
            },
        ),
        migrations.CreateModel(
            name="SaleChannel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("is_only_for_verified_user", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "price_source",
                    models.CharField(
                        choices=[("fake", "Fake"), ("csv", "CSV"), ("generated", "Generated"), ("api", "API")],
                        default="fake",
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_channels",
                        to="django_pricemanager.channel",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_regional.country"),
                ),
                (
                    "customer_representation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_channels",
                        to="django_pricemanager.customerrepresentation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "sale channels",
                "ordering": ["idx"],
            },
        ),
        migrations.AddField(
            model_name="pricelist",
            name="sale_channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_lists",
                to="django_pricemanager.salechannel",
            ),
        ),
        migrations.AddField(
            model_name="productrepresentation",
            name="tax_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_representations",
                to="django_pricemanager.taxclass",
            ),
        ),
        migrations.AddField(
            model_name="attributerepresentation",
            name="tax_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attr_representations",
                to="django_pricemanager.taxclass",
            ),
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rate", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "country",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_regional.country"),
                ),
                (
                    "tax_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_rates",
                        to="django_pricemanager.taxclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gross_value", models.DecimalField(decimal_places=4, max_digits=19)),
                ("net_value", models.DecimalField(decimal_places=4, max_digits=19)),
                ("special_gross_value", models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ("special_net_value", models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("csv_import", "CSV Import"),
                            ("api", "API"),
                            ("generation", "Generation"),
                            ("admin_edit", "Admin Edit"),
                            ("tax_rate_change", "Tax Rate Change"),
                            ("migration", "Migration"),
                            ("migration_backfill", "Migration Backfill"),
                            ("supplier_cost", "Supplier Cost"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_pricemanager.channel"),
                ),
                (
                    "country",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_regional.country"),
                ),
                (
                    "currency",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_regional.currency"),
                ),
                (
                    "customer_representation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_pricemanager.customerrepresentation",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="django_pricemanager.productrepresentation",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="django_pricemanager.taxrate",
                    ),
                ),
            ],
            options={
                "verbose_name": "price history",
                "verbose_name_plural": "price history",
                "db_table": "pricemanager_pricehistory",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="price",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prices",
                to="django_pricemanager.taxrate",
            ),
        ),
        migrations.AddField(
            model_name="currentprice",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="django_pricemanager.taxrate",
            ),
        ),
        migrations.AddConstraint(
            model_name="priceattribute",
            constraint=models.UniqueConstraint(fields=("price", "attr"), name="unique_price_attribute"),
        ),
        migrations.AddIndex(
            model_name="purchasecost",
            index=models.Index(fields=["product", "channel"], name="pricemanage_product_7b0f57_idx"),
        ),
        migrations.AddIndex(
            model_name="purchasecost",
            index=models.Index(fields=["product"], name="pricemanage_product_7d5795_idx"),
        ),
        migrations.AddConstraint(
            model_name="purchasecost",
            constraint=models.UniqueConstraint(
                fields=("product", "channel", "country", "currency"), name="unique_purchase_cost"
            ),
        ),
        migrations.AddConstraint(
            model_name="productrepresentation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("sku"), name="unique_pricemanager_product_sku"
            ),
        ),
        migrations.AddConstraint(
            model_name="attributerepresentation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("idx"), name="unique_pricemanager_product_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taxrate",
            unique_together={("tax_class", "country")},
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["product", "channel", "country", "currency", "-created_at"],
                name="pricemanage_product_3724fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(fields=["channel", "-created_at"], name="pricemanage_channel_269b5f_idx"),
        ),
        migrations.AddIndex(
            model_name="currentprice",
            index=models.Index(fields=["channel", "country", "currency"], name="pricemanage_channel_8ef52f_idx"),
        ),
        migrations.AddIndex(
            model_name="currentprice",
            index=models.Index(fields=["product", "channel"], name="pricemanage_product_efbeee_idx"),
        ),
        migrations.AddIndex(
            model_name="currentprice",
            index=models.Index(fields=["product"], name="pricemanage_product_3881a5_idx"),
        ),
        migrations.AddConstraint(
            model_name="currentprice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("customer_representation__isnull", True), ("product_parent__isnull", True)),
                fields=("product", "channel", "country", "currency"),
                name="unique_current_price_general",
            ),
        ),
        migrations.AddConstraint(
            model_name="currentprice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("customer_representation__isnull", True), ("product_parent__isnull", False)),
                fields=("product", "product_parent", "channel", "country", "currency"),
                name="unique_current_price_general_bundle",
            ),
        ),
        migrations.AddConstraint(
            model_name="currentprice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("customer_representation__isnull", False), ("product_parent__isnull", True)),
                fields=("product", "channel", "country", "currency", "customer_representation"),
                name="unique_current_price_customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="currentprice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("customer_representation__isnull", False), ("product_parent__isnull", False)),
                fields=("product", "product_parent", "channel", "country", "currency", "customer_representation"),
                name="unique_current_price_customer_bundle",
            ),
        ),
    ]
