# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-19 11:17

from collections import defaultdict

from django.db import migrations, models


def dedupe_channel_idx(apps, schema_editor):
    """Guard for the AddConstraint below — no prior migration enforced Channel.idx uniqueness,
    so a duplicate here would otherwise abort the deploy. Keeps the lowest-pk row's idx
    untouched and suffixes the rest so the constraint can be added safely.
    """
    Channel = apps.get_model("django_pricemanager", "Channel")
    pks_by_idx = defaultdict(list)
    for channel in Channel.objects.order_by("pk").only("pk", "idx"):
        pks_by_idx[channel.idx].append(channel.pk)

    for idx, pks in pks_by_idx.items():
        for position, pk in enumerate(pks[1:], start=1):
            Channel.objects.filter(pk=pk).update(idx=f"{idx}-dup{position}-{pk}")


class Migration(migrations.Migration):
    dependencies = [
        ("django_pricemanager", "0024_remove_currentprice_supplier_cost_fields"),
        ("django_regional", "0006_country_default_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceSourcePolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("csv_import", "CSV Import"),
                            ("api", "API"),
                            ("generation", "Generation"),
                            ("admin_edit", "Admin Edit"),
                            ("tax_rate_change", "Tax Rate Change"),
                            ("migration", "Migration"),
                            ("migration_backfill", "Migration Backfill"),
                            ("supplier_cost", "Supplier Cost"),
                            ("pricefighter", "PriceFighter"),
                            ("baseline", "Baseline"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("recalc_overwritable", models.BooleanField(default=False)),
                (
                    "enforce_mode",
                    models.CharField(
                        choices=[("clamp", "Clamp to bounds"), ("reject", "Reject write")],
                        default="clamp",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "price source policy",
                "verbose_name_plural": "price source policies",
                "db_table": "pricemanager_pricesourcepolicy",
            },
        ),
        migrations.AlterField(
            model_name="currentprice",
            name="source",
            field=models.CharField(
                choices=[
                    ("csv_import", "CSV Import"),
                    ("api", "API"),
                    ("generation", "Generation"),
                    ("admin_edit", "Admin Edit"),
                    ("tax_rate_change", "Tax Rate Change"),
                    ("migration", "Migration"),
                    ("migration_backfill", "Migration Backfill"),
                    ("supplier_cost", "Supplier Cost"),
                    ("pricefighter", "PriceFighter"),
                    ("baseline", "Baseline"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="source",
            field=models.CharField(
                choices=[
                    ("csv_import", "CSV Import"),
                    ("api", "API"),
                    ("generation", "Generation"),
                    ("admin_edit", "Admin Edit"),
                    ("tax_rate_change", "Tax Rate Change"),
                    ("migration", "Migration"),
                    ("migration_backfill", "Migration Backfill"),
                    ("supplier_cost", "Supplier Cost"),
                    ("pricefighter", "PriceFighter"),
                    ("baseline", "Baseline"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(dedupe_channel_idx, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.UniqueConstraint(fields=("idx",), name="unique_channel_idx"),
        ),
    ]
