# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-19 11:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_pricemanager", "0025_pricesourcepolicy_alter_currentprice_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceBoundsConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "map_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Minimum Advertised Price, GROSS, absolute amount in the market's currency.",
                        max_digits=19,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_margin_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Minimum margin over PurchaseCost.net_cost, e.g. 0.05 = 5%.",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_bounds",
                        to="django_pricemanager.channel",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_bounds",
                        to="django_pricemanager.productrepresentation",
                    ),
                ),
            ],
            options={
                "verbose_name": "price bounds config",
                "verbose_name_plural": "price bounds configs",
                "db_table": "pricemanager_priceboundsconfig",
                "indexes": [models.Index(fields=["product", "channel"], name="pricemanage_product_b4083e_idx")],
            },
        ),
    ]
