# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-19 11:31

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_pricemanager", "0026_priceboundsconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="baseline_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BaselineConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "markup_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.2000"),
                        help_text="e.g. 0.2000 = 20% markup over PurchaseCost.net_cost.",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "rounding",
                    models.CharField(
                        choices=[
                            ("none", "No rounding"),
                            (".99", "Round to .99"),
                            (".95", "Round to .95"),
                            ("int", "Round to integer"),
                        ],
                        default="none",
                        max_length=8,
                    ),
                ),
                (
                    "channel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline_config",
                        to="django_pricemanager.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "baseline config",
                "verbose_name_plural": "baseline configs",
                "db_table": "pricemanager_baselineconfig",
            },
        ),
        migrations.CreateModel(
            name="BaselineTombstone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline_tombstones",
                        to="django_pricemanager.channel",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline_tombstones",
                        to="django_pricemanager.productrepresentation",
                    ),
                ),
            ],
            options={
                "verbose_name": "baseline tombstone",
                "verbose_name_plural": "baseline tombstones",
                "db_table": "pricemanager_baselinetombstone",
                "constraints": [
                    models.UniqueConstraint(fields=("product", "channel"), name="unique_baseline_tombstone")
                ],
            },
        ),
    ]
