# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_pricemanager", "0027_channel_baseline_enabled_baselineconfig_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="priceboundsconfig",
            constraint=models.UniqueConstraint(
                fields=("product", "channel"), name="pricebounds_unique_scope", nulls_distinct=False
            ),
        ),
    ]
